stages:
  - test
  - publish

test-debug:
  image: openjdk:8
  stage: test
  script:
    - ./gradlew build

release:
  image: openjdk:8
  stage: publish
  only:
    - master
  script:
    - ./gradlew artifactPublish -Partifactory_user=$ARTIFACTORY_USERNAME -Partifactory_password=$ARTIFACTORY_PASSWORD

